name: pvpstats
main: net.slipcor.pvpstats.$
version: ${project.version}
author: [slipcor, yiwan]
depend: [SimpleORM]
softdepend: [pvparena,PlaceholderAPI, LeaderHeads]
website: http://dev.bukkit.org/server-mods/pvp-stats/
commands:
    pvpstats:
        description: handle PvP stats
        aliases: stats
permissions:
    pvpstats.reload:
        description: Ability to reload
        default: op
    pvpstats.give_point:
        description: Ability to give point
        default: op
    pvpstats.cleanup:
        description: Ability to cleanup
        default: op
    pvpstats.purge:
        description: Ability to purge
        default: op
    pvpstats.wipe:
        description: Ability to wipe
        default: op
    pvpstats.debug:
        description: Ability to debug
        default: op
    pvpstats.count:
        description: Permission to be counted
        default: true
    pvpstats.newbie:
        description: Permission to block being killed to be counted
        default: false
    pvpstats.top:
        description: Permission to get global stats
        default: true
